# Generated by Django 5.1.5 on 2025-03-29 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_alter_match_team1_alter_match_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='tournament.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='tournament.team'),
        ),
    ]
