# Generated by Django 5.1.5 on 2025-03-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_tournament_max_teams_alter_match_team1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
